### ISSUE TITLE
Produces invalid URI for large png

### ISSUE THREAD

**Issue by m59peacemaker** [asbjornenge/imgurify#1]
I am able to base64 encode this image using other means and it loads in the browser, but bundling with browserify and imgurify is producing an invalid uri.

https://github.com/m59peacemaker/game/blob/master/src/assets/hero.png (4.5mb)

Small pngs are working fine, but I as have this problem with another png that is around 90k. It seems like the transform is bugged for larger files.

**Comment by asbjornenge** [comment]
According to the Data URL spec there is 1024 byte size limitation. More info [here](http://dataurl.net/#about) (see Size limitations under Disadvantages).

I think `imgurify` encodes the image correctly. I tried your `hero.png` with the cli and it works. I think your issue is due to the browser(s) not wanting to render such large data urls.

**Comment by m59peacemaker** [comment]
@asbjornenge Makes sense! Thanks!

**Comment by Prinzhorn** [comment]
It actually does produce invalid base64. I assume because the buffer is read as utf8 by browserify and you can't just toString('base64') it because some of the binary info is already lost.

Here's a gif animation I was trying to base64. The data uri generated by imgurify does not work but the one generated by http://dopiaza.org/tools/datauri/index.php does (despite the 1024 byte limit). They both have the **exact same size** but with completely **different contents**. Here are the last bytes of both

```
aogibYgi74gjAYgzI4gzRYgzZogwNBAINACIUQAIZwCIjgB4LQByg4giMYgiQICILgBxRIERsRAIlAAIoQEAA7

Im2IIu+IIwGIMyOIM0WIM2aIMDQQCDQAiFEACGcAiI4AeC0AcoOIIjGIIkCAiC4AcUSBEbEQCJQACKEBAAOw==
```

Here's the gif http://www.prinzhorn.me/spinner.gif

See http://stackoverflow.com/questions/3709391/node-js-base64-encode-a-downloaded-image-for-use-in-data-uri for details

I can't do further research now but will take a look at it tomorrow. Could be that I'm wrong.

**Comment by Prinzhorn** [comment]
I found the issue. Once the buffer is larger than 65536 bytes, this line is executed twice. In case of my gif once with a buffer of size 65536 and then with 23484 bytes.

``` js
function (buf, enc, next) { i++; this.push(rasterHead(i,type)); this.push(buf.toString('base64')); next() },
```

but you can't just split base64 encoding that way (you can't encode the two parts separately and then simply concat it).

**Comment by asbjornenge** [comment]
@Prinzhorn Aha! Should be as simple as concat the raw input and then base64 in the `end` function then...? I'll get started on a fix straight away! :smile: :+1:

**Comment by asbjornenge** [comment]
Fix out on npm - imgurify@1.2.1 :rocket: 
@Prinzhorn thanks a bunch for debugging the issues!
@m59peacemaker sorry for not investigating further before :wink:

**Comment by Prinzhorn** [comment]
thanks!

**Comment by asbjornenge** [comment]
@Prinzhorn let me know if you have further issues :smile:

**Comment by m59peacemaker** [comment]
Neat. No problem =D
